### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by zinovik** [zinovik/z-games-api#34]

**Comment by zinovik** [comment]
Hello, Richard
It sounds cool! Are you offer your help for free?

**Comment by richardbmx** [comment]
@zinovik  if it's completely free

**Comment by zinovik** [comment]
@richardbmx, yeah, it's completely free at the moment

**Comment by richardbmx** [comment]
@zinovik  perfect can you explain to me a bit about what the project is about ??

**Comment by zinovik** [comment]
@richardbmx, sure.
It's web application for playing board games. It's kind of tiny board games portal.
There are only two games at the moment: No, Thanks! and Perudo.
You can check current version here: https://z-games.herokuapp.com

**Comment by richardbmx** [comment]
Starting from the base color of your website and using the letter Z as the main symbol I present this idea with a minimalist style giving a particular shape to the letter Z and easily converting into a favicon or icon, very versatile in different backgrounds and colors what makes it a flexible image and easy to adapt.

If you want some change you just have to ask for it, if you want to use it I can create a PR with the incorporation of the logo. ;-)

![logo952](https://user-images.githubusercontent.com/35604837/50521752-8d672080-0a9d-11e9-9ce0-8d72a307ff77.png)

**Comment by zinovik** [comment]
@richardbmx, good job! Looks really cool, I like it. But it would be better to use 'games' in plural form for all variants. Sure you could make PR ;)

**Comment by richardbmx** [comment]
perfect I'll make the changes and make the PR

**Comment by richardbmx** [comment]
@zinovik  Here I give you a folder of google drive with all the editable files to use the logo in its two horizontal and vertical versions, if you want some change you just have to ask for it.

[GoogleDrive](https://drive.google.com/open?id=1x2lGpeW2XRjGR18H3-xCl8mKLid7awYA)

**Comment by zinovik** [comment]
@richardbmx, thank you for your work. I have merged your pull request ;)
Could you add also favicon.ico?

**Comment by richardbmx** [comment]
@zinovik  add the favicon version of the logo in the google folder ;-)
![favicon1](https://user-images.githubusercontent.com/35604837/50539220-07a5ac80-0b53-11e9-82c0-9e9b6cd3a7fc.png)
![faviconbw](https://user-images.githubusercontent.com/35604837/50539221-07a5ac80-0b53-11e9-9505-ba3bbbc681a8.png)

**Comment by zinovik** [comment]
@richardbmx, thank you!
